version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6377:6377"
    networks:
      - serverNet
  pgsql:
    image: postgres:9-alpine
    container_name: nanopgsql
    restart: unless-stopped
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "114514"
      POSTGRES_DB: "serverDB"
    networks:
      - serverNet
  server:
    build: .
    container_name: management-server
    depends_on:
      - redis
      - pgsql
    ports:
      - "10100:10100"
    networks:
      - serverNet
volumes:
  my-vol: { }

networks:
  serverNet:
    name: serverNet
