version: '3.7'
services:
  redis:
    image: redis
    ports:
        - "6379:6379"
  pgsql:
    image: postgres:9-alpine
    container_name: nanopgsql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD:  "pass"
      POSTGRES_DB:  "serverDB"
  server:
    build: .
    container_name: management-server
    depends_on:
        - redis
        - pgsql
    ports:
        - "10100:10100"
volumes:
  my-vol: {}
